### ISSUE TITLE
Access to pretrained model

### ISSUE THREAD

**Issue by Carinazhao22** [nis-research/afa-augment#1]
Dear,
 
Thanks for your great work. I am wondering if you would like to provide pretrained models about your paper. I just sent the request to access your pretrained weights but haven't got approval yet. Thanks in advance! 

Carina

**Comment by Tenbatsu24** [comment]
Hello Carina,

 It turns out due to data policy, the account through which the model weights were shared was removed and we didn't get any updates on it. However, we have the model weights now moved to [zenodo](https://zenodo.org/records/13755777) (https://zenodo.org/records/13755777) as well. Please free to access the pretrained model weights from there instead. We also provide the model weights at the end of the training in a seperate zip file (last_checkpoints) in case you want to resume training.

 Hopefully this is helpful. Thank you for bringing this to our attention and happy ml!

Mei
