### ISSUE TITLE
Python version used for the project

### ISSUE THREAD

**Issue by sahanHe** [nis-research/afa-augment#2]
Hi,

For this project, is there any specific version for the python used?

**Comment by Tenbatsu24** [comment]
We used python=3.10 during development but we did not test it for lower python versions. Are there any errors you can share for the project so that I recommend a solution?

**Comment by sahanHe** [comment]
Hi, 
I was able to solve this issue and run the model. Previously I had a issue with the configuration as in the example it was given as "rn50dubin" but actually it should have been "rn50_dubin", I was wondering whether the error was caused by dependency issues. [commit](https://github.com/nis-research/afa-augment/compare/main...sahanHe:afa-augment:main)

In addition to the above issue, I had some concerns about the exact configurations used for getting the results of table 2. as configurations doesn't have option to enable AugMax. And I would also like to know how to properly configure the model to have AugMax as the primary augmentation and fav as Auxiliary one as in the table2.

**Comment by Tenbatsu24** [comment]
Hi again,

 I am glad you were able to solve the issue. I will change the example to reflect the correct string. 

 We do not implement AugMax in our release of the code since the authors of AugMax provide the implementation themselves and we found it difficult to integrate their method in our repository. Therefore, we thought best not to provide a possibly faulty implementation as part of our code repository. We used the results they provided in their paper directly. Our method also does not integrate with AugMax since augmax provides an auxiliary augmentation as well. AFA in that sense is a replacement to AugMax.

**Comment by sahanHe** [comment]
@Tenbatsu24 Thanks for the response, that makes sense regarding the experiments.

And talking about the AFA augmentation, is it enough to add AFA as a attack type in the configuration or should I enable `use_fourier` flag in the configurations?

**Comment by Tenbatsu24** [comment]
@sahanHe It is enough to add AFA as attack type. use_fourier = True is for enabling it as a main augmentation (i.e. in place of visual augmentation) which is not recommended as we show in our ablations.
